using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IdaNet.IdaInterop
{
    internal enum NameListFlags : byte
    {
        LN_NORMAL = 0x01, //< include normal names
        LN_PUBLIC = 0x02, //< include public names
        LN_AUTO = 0x04, //< include autogenerated names
        LN_WEAK = 0x08, //< include weak names
    }
}
