using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ManagedPlugin.IdaNet.IdaInterop
{
    public enum SetNameFlags : ushort
    {
        SN_CHECK = 0x00,
        SN_NOCHECK = 0x01, //< Don't fail if the name contains invalid characters.
        SN_PUBLIC = 0x02, //< if set, make name public
        SN_NON_PUBLIC = 0x04, //< if set, make name non-public
        SN_WEAK = 0x08, //< if set, make name weak
        SN_NON_WEAK = 0x10, //< if set, make name non-weak
        SN_AUTO = 0x20, //< if set, make name autogenerated
        SN_NON_AUTO = 0x40, //< if set, make name non-autogenerated
        SN_NOLIST = 0x80, //< if set, exclude name from the list.
        SN_NOWARN = 0x100, //< don't display a warning if failed
        SN_LOCAL = 0x200, //< create local name. a function should exist.
        SN_IDBENC = 0x400, //< the name is given in the IDB encoding;
        SN_FORCE = 0x800, //< if the specified name is already present
        SN_NODUMMY = 0x1000, //< automatically prepend the name with '_' if it
        SN_DELTAIL = 0x2000, //< if name cannot be set because of a tail byte,
    }
}
