using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IdaNet.IdaInterop
{
    internal enum StringLiteralFlags : byte
    {
        STRF_GEN = 0x01, //< generate names?
        STRF_AUTO = 0x02, //< names have 'autogenerated' bit?
        STRF_SERIAL = 0x04, //< generate serial names?
        STRF_UNICODE = 0x08, //< unicode strings are present?
        STRF_COMMENT = 0x10, //< generate auto comment for string references?
        STRF_SAVECASE = 0x20, //< preserve case of strings for identifiers
    }
}
